FROM fedora:34

<%= snippet('labels', binding) -%>

<%= snippet('docker-entrypoint', binding) -%>

<%= snippet('dockerize', binding) -%>

<%= snippet('tini', binding) -%>

RUN \
   dnf -y \
     --setopt=tsflags=nodocs \
     --setopt=override_install_langs=en_US.utf8 \
     --setopt=install_weak_deps=False install file \
     open-vm-tools \
     net-tools \
     iproute \
&& dnf clean all

ENTRYPOINT ["/tini", "--", "/docker-entrypoint.sh"]
CMD /usr/bin/vmtoolsd
